"""Fetch a threat report (URL or local file) and extract observables/TTPs
from it with plain regexes — no network SDKs, no NLP model, no external
API calls, consistent with the rest of this tool.

This is a heuristic best-effort extractor, not a CTI parsing engine.
Treat its output — especially `suggest_cluster_names` — as a starting
point for an agent (or analyst) to confirm, not as ground truth. It will
both miss things (PDFs are out of scope; obfuscated/imaged IOCs won't be
seen) and occasionally over-match (e.g. a version string that happens to
look like an IP). `core.ingest_report` refuses to guess a cluster name
when extraction is ambiguous rather than silently filing a report under
the wrong actor — see its docstring.
"""
from __future__ import annotations

import html
import ipaddress
import re
import shutil
import subprocess
import tempfile
import urllib.request
from collections import Counter
from pathlib import Path

USER_AGENT = "cti-agent-report-ingest/1.0 (+local analysis tool, no telemetry)"
FETCH_TIMEOUT = 20

# The observable categories a cluster tracks, in a single place so the
# extractor, the core data model, STIX export, and the CLI all agree on
# the set. "hashes/domains/ips/urls" are the original network-infra
# indicators; "emails/cves/wallets" were added later. The "ja4*"/"jarm"
# categories are the full JA4+ suite (FoxIO) plus JARM (Salesforce) -
# network/TLS/TCP/SSH fingerprints of adversary infrastructure. Unlike
# every other category, these are never populated by regex extraction
# from report text: they're generated by actively fingerprinting an
# already-tracked domain/IP (e.g. from an isolated vantage point) and
# filed by hand with add_observable. Extraction returns one list per
# category (plus "ttps", which is handled separately since it isn't an
# observable).
OBSERVABLE_CATEGORIES = (
    "hashes", "domains", "ips", "urls", "emails", "cves", "wallets",
    # JA4+ suite (FoxIO): client/server TLS, HTTP, latency, cert, TCP, SSH.
    "ja4", "ja4s", "ja4h", "ja4l", "ja4x", "ja4t", "ja4ts", "ja4ssh",
    # JARM (Salesforce): active TLS server fingerprint, distinct algorithm from JA4S.
    "jarm",
)

# Deliberately curated, not exhaustive: generic TLDs plus ccTLDs/newer
# gTLDs that show up disproportionately often in malicious infrastructure
# reporting. A hostname whose TLD isn't in this set is dropped rather
# than risking false positives on arbitrary "word.word" text. Extend
# this list if your reports keep missing legitimate domains.
_TLDS = {
    "com", "net", "org", "info", "biz", "io", "co", "me", "us", "uk",
    "de", "fr", "nl", "ru", "su", "cn", "hk", "tw", "jp", "kr", "in",
    "br", "pl", "es", "it", "se", "no", "fi", "dk", "ch", "at", "be",
    "cc", "tv", "ws", "to", "cf", "ga", "gq", "ml", "tk", "top", "xyz",
    "site", "online", "club", "icu", "live", "shop", "store", "fun",
    "vip", "buzz", "space", "click", "link", "download", "stream",
    "work", "rest", "cyou", "monster", "bond", "cam", "pw", "sh",
    "app", "dev", "cloud", "host", "pro", "biz", "name", "email",
}

_HASH_PATTERNS = {
    "sha256": re.compile(r"\b[A-Fa-f0-9]{64}\b"),
    "sha1": re.compile(r"\b[A-Fa-f0-9]{40}\b"),
    "md5": re.compile(r"\b[A-Fa-f0-9]{32}\b"),
}
_IP_PATTERN = re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")
# Loose IPv6 matcher — deliberately over-broad; every hit is validated
# with ipaddress.ip_address() below, so a false match just gets dropped.
_IPV6_PATTERN = re.compile(r"\b(?:[A-Fa-f0-9]{0,4}:){2,7}[A-Fa-f0-9]{0,4}\b")
# Direct "ip:port" adjacency, e.g. a bare "206.238.115.58:886" in text
# (not a URL — no scheme). Unambiguous when it matches.
_IP_PORT_INLINE_PATTERN = re.compile(r"\b((?:\d{1,3}\.){3}\d{1,3}):(\d{2,5})\b")
# Prose naming a C2/service port near the IP(s) it applies to without
# direct adjacency, e.g. "Atlas RAT: TCP port 886 (IPs: 1.2.3.4, 5.6.7.8)"
# or "listens on port 1234". _extract_ip_ports() below pairs each match
# with any already-extracted IP found in the same "chunk" of text (see
# _SENTENCE_SPLIT_RE).
_PORT_MENTION_PATTERN = re.compile(
    r"\b(?:TCP|UDP)?\s*port\s*[:#]?\s*(\d{2,5})\b", re.IGNORECASE)
# Splits report text into sentence-or-line-sized chunks for
# _extract_ip_ports()'s proximity pass: a sentence-ending punctuation
# mark followed by whitespace, or a newline. HTML-stripped report text
# often loses paragraph breaks but keeps sentence punctuation, and a
# bullet-list report keeps newlines even without terminal periods -
# covering both keeps "<malware>: TCP port N (IP: ...)." style clauses
# (the common phrasing this targets) each in their own chunk regardless
# of which form the source report uses.
_SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?])\s+|\n+")
# A "chunk" (see above) longer than this isn't trusted as one semantic
# unit for port<->IP pairing - an unpunctuated run of text this long is
# more likely garbled/lost formatting than a single real sentence, and
# pairing every IP in it with whatever port also happens to appear
# would be a guess dressed up as an association.
_MAX_PORT_CHUNK_LEN = 400
_URL_PATTERN = re.compile(r"https?://[^\s\"'<>\)\]]+", re.IGNORECASE)
_DOMAIN_CANDIDATE = re.compile(
    r"\b(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+"
    r"([a-zA-Z]{2,24})\b"
)
_TTP_PATTERN = re.compile(r"\bT1\d{3}(?:\.\d{3})?\b")
_EMAIL_PATTERN = re.compile(
    r"\b[A-Za-z0-9._%+-]+@((?:[A-Za-z0-9-]+\.)+([A-Za-z]{2,24}))\b")
_CVE_PATTERN = re.compile(r"\bCVE-\d{4}-\d{4,7}\b", re.IGNORECASE)
# Crypto wallets: bech32 Bitcoin (bc1...) and Ethereum-style 0x + 40 hex.
# Legacy base58 Bitcoin addresses are intentionally NOT matched — their
# charset is too permissive and produces frequent false positives on
# ordinary alphanumeric tokens; bech32 and 0x forms are self-delimiting
# enough to stay precise.
_WALLET_PATTERNS = [
    re.compile(r"\bbc1[a-z0-9]{25,87}\b"),
    re.compile(r"\b0x[a-fA-F0-9]{40}\b"),
]

# Naming conventions from the major vendor taxonomies. Best-effort:
# these catch the common cases, not every alias scheme in use.
_NAME_PATTERNS = [
    # Microsoft weather-themed actor names, e.g. "Volt Typhoon"
    re.compile(r"\b[A-Z][a-z]+\s+(?:Tempest|Typhoon|Blizzard|Sandstorm|Sleet|Storm|Flood|Hail|Dust)\b"),
    # CrowdStrike animal-themed adversary names, e.g. "Fancy Bear"
    re.compile(r"\b[A-Z][a-z]+\s+(?:Spider|Panda|Bear|Kitten|Jackal|Chollima|Buffalo|Tiger|Ocelot|Crane|Wolf|Fox)\b"),
    # Mandiant / Proofpoint / Secureworks numbered clusters
    re.compile(r"\b(?:APT|FIN|UNC|TA|GOLD|BRONZE|COPPER|TIN)[\s-]?\d{2,5}\b", re.IGNORECASE),
    # "<Name> ransomware/malware/loader/..." — malware family names
    re.compile(r"\b([A-Z][A-Za-z0-9]{2,20})(?=\s+(?:ransomware|malware|loader|backdoor|trojan|stealer|botnet|worm))\b"),
]

_DEFANG_SUBS = [
    (re.compile(r"hxxps", re.IGNORECASE), "https"),
    (re.compile(r"hxxp", re.IGNORECASE), "http"),
    (re.compile(r"\[\.\]|\(\.\)|\{\.\}"), "."),
    (re.compile(r"\[dot\]|\(dot\)", re.IGNORECASE), "."),
    (re.compile(r"\[://\]|\(://\)"), "://"),
    (re.compile(r"\[:\]|\(:\)"), ":"),
    (re.compile(r"\[at\]|\(at\)|\[@\]", re.IGNORECASE), "@"),
]


class UnsupportedSource(Exception):
    pass


def defang_normalize(text: str) -> str:
    """Undo common IOC defanging (hxxp, [.], etc.) so regexes can match
    normally. Reports defang IOCs specifically so they don't get treated
    as live links/clicked by accident — this tool re-fangs them purely
    in memory for extraction, nothing here fetches or resolves them."""
    for pattern, repl in _DEFANG_SUBS:
        text = pattern.sub(repl, text)
    return text


def _strip_html(raw: str) -> str:
    raw = re.sub(r"(?is)<(script|style)[^>]*>.*?</\1>", " ", raw)
    raw = re.sub(r"(?s)<[^>]+>", " ", raw)
    return html.unescape(raw)


def _pdftotext(path: str) -> str:
    """Extract text from a local PDF via the `pdftotext` CLI (poppler).
    Kept as an external binary rather than a Python PDF dependency so the
    package's zero-runtime-deps posture holds; if poppler isn't installed
    we fall back to the same instructive error as before."""
    exe = shutil.which("pdftotext")
    if not exe:
        raise UnsupportedSource(
            "PDF source given but `pdftotext` (poppler-utils) isn't installed; "
            "install it, or extract the text yourself (e.g. "
            "`pdftotext report.pdf report.txt`) and pass the .txt file")
    try:
        # "-" writes the extracted text to stdout; "-q" suppresses noise.
        out = subprocess.run([exe, "-q", path, "-"], capture_output=True,
                             timeout=FETCH_TIMEOUT, check=True)
    except subprocess.CalledProcessError as e:
        raise UnsupportedSource(f"pdftotext failed on {path}: "
                                f"{e.stderr.decode('utf-8', 'replace').strip()}") from e
    except subprocess.TimeoutExpired as e:
        raise UnsupportedSource(f"pdftotext timed out on {path}") from e
    return out.stdout.decode("utf-8", errors="replace")


def fetch_text(source: str) -> str:
    """Return plain text for a URL or local file path. HTML is stripped
    to text; PDFs are extracted via `pdftotext` if poppler-utils is
    installed (otherwise a clear error asks you to extract the text
    first). Other binary formats are unsupported."""
    is_pdf = source.lower().endswith(".pdf")

    if source.startswith(("http://", "https://")):
        req = urllib.request.Request(source, headers={"User-Agent": USER_AGENT})
        with urllib.request.urlopen(req, timeout=FETCH_TIMEOUT) as resp:
            content_type = resp.headers.get_content_type()
            body = resp.read()
        if is_pdf or content_type == "application/pdf":
            # pdftotext needs a real file; buffer the download and clean up.
            with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tf:
                tf.write(body)
                tmp = tf.name
            try:
                return _pdftotext(tmp)
            finally:
                Path(tmp).unlink(missing_ok=True)
        raw = body.decode(resp.headers.get_content_charset() or "utf-8", errors="replace")
        if content_type == "text/html":
            return _strip_html(raw)
        return raw

    p = Path(source)
    if not p.exists():
        raise FileNotFoundError(f"no such file: {source}")
    if is_pdf:
        return _pdftotext(str(p))
    raw = p.read_text(errors="replace")
    if p.suffix.lower() in (".htm", ".html"):
        return _strip_html(raw)
    return raw


def _extract_ip_ports(text: str, ips: list[str]) -> dict[str, list[int]]:
    """Best-effort IP->port(s) association for report prose that names a
    C2/service port near (not necessarily immediately adjacent to) the
    IP(s) it applies to, e.g. "Atlas RAT: TCP port 886 (IPs: 1.2.3.4,
    5.6.7.8). RomulusLoader: TCP port 1234 (IP: 9.9.9.9)." `ips` should
    be the already-extracted, already-validated (private/reserved
    filtered) list from this same text — only IPs in that list are
    eligible to receive a port here.

    Two passes, most-confident first:

    1. Direct "ip:port" adjacency (e.g. a bare "1.2.3.4:8080" with no
       URL scheme) - unambiguous, always wins for that IP.
    2. Text is split into sentence/line-sized chunks (_SENTENCE_SPLIT_RE)
       and, within each chunk short enough to trust (_MAX_PORT_CHUNK_LEN),
       every IP is paired with that chunk's port - but only if the chunk
       names exactly one distinct port. A plain character-distance
       window instead of chunk boundaries was tried first and rejected:
       it let a port mention in one clause "win" an IP that actually
       belongs to an adjacent clause's port whenever the two clauses sat
       close together (e.g. two back-to-back "<malware>: TCP port N
       (IP: ...)." sentences) purely because raw distance happened to
       favor it - a chunk is the actual unit a report author associates
       a port with, so containment beats distance here. A chunk naming
       more than one distinct port is ambiguous and skipped rather than
       guessed at.

    Returns every distinct port found for an IP across all unambiguous
    mentions in the whole text (deduped, in the order first seen) - not
    just the first. A C2 genuinely running on more than one port shows up
    in report prose as more than one unambiguous mention (a direct
    "ip:port" plus a separate proximity sentence, or two separate
    single-port sentences naming the same IP), and each of those is
    independently just as trustworthy as if it were the only mention in
    the report - there's no reason a second, equally-unambiguous mention
    should lose to whichever happened to be found first. What still makes
    a single *mention* untrustworthy - and so still skipped rather than
    guessed at - is unchanged: a chunk naming more than one distinct port
    with no way to tell which IP goes with which.

    Ports outside 1-65535 (a `\\d{2,5}` match that isn't actually a valid
    port, e.g. incidentally matching part of a longer number) are
    dropped."""
    ip_set = set(ips)
    resolved: dict[str, list[int]] = {}

    def _add(ip: str, port: int) -> None:
        ports = resolved.setdefault(ip, [])
        if port not in ports:
            ports.append(port)

    for ip, port_str in _IP_PORT_INLINE_PATTERN.findall(text):
        if ip in ip_set:
            port = int(port_str)
            if 1 <= port <= 65535:
                _add(ip, port)

    for chunk in _SENTENCE_SPLIT_RE.split(text):
        if len(chunk) > _MAX_PORT_CHUNK_LEN:
            continue
        ports_in_chunk = {int(p) for p in _PORT_MENTION_PATTERN.findall(chunk)}
        ports_in_chunk = {p for p in ports_in_chunk if 1 <= p <= 65535}
        if len(ports_in_chunk) != 1:
            continue  # no port mentioned, or more than one distinct value - ambiguous
        port = next(iter(ports_in_chunk))
        for ip in _IP_PATTERN.findall(chunk):
            if ip in ip_set:
                _add(ip, port)

    return resolved


def extract_observables(text: str) -> dict[str, list[str]]:
    """Pull hashes/IPs/domains/URLs/emails/CVEs/crypto-wallets and ATT&CK
    technique IDs out of report text. Input should already be
    defang-normalized. Returns one list per OBSERVABLE_CATEGORIES key
    plus "ttps" and "ip_ports". The ja4*/jarm categories are always
    empty here - report text doesn't carry TLS/TCP/SSH fingerprints of
    infrastructure you haven't probed yourself; those are filed via
    add_observable instead, see OBSERVABLE_CATEGORIES. "ip_ports" is a
    {ip: [port, ...]} map, not an observable category of its own - every
    C2 port a report unambiguously names near one of the extracted IPs
    (see _extract_ip_ports; usually one port, but a genuinely
    multi-port C2 can turn up more than one), used downstream so active
    fingerprinting probes that IP's actual service port(s) instead of
    always defaulting to 443."""
    urls = sorted(set(_URL_PATTERN.findall(text)))

    ips = []
    for m in _IP_PATTERN.findall(text) + _IPV6_PATTERN.findall(text):
        try:
            addr = ipaddress.ip_address(m)
        except ValueError:
            continue
        if addr.is_private or addr.is_loopback or addr.is_link_local \
                or addr.is_multicast or addr.is_reserved or addr.is_unspecified:
            continue  # not useful as adversary infrastructure
        ips.append(addr.compressed)
    ips = sorted(set(ips))

    domains = set()
    for m in _DOMAIN_CANDIDATE.finditer(text):
        tld = m.group(1).lower()
        if tld in _TLDS:
            domains.add(m.group(0).rstrip("."))
    domains = sorted(domains)

    # Longest-match-first so a sha256 substring can't also register as
    # an md5/sha1 hit — word boundaries already prevent this in practice
    # since hex runs are contiguous word characters, but keep it explicit.
    hashes: dict[str, str] = {}
    for algo in ("sha256", "sha1", "md5"):
        for m in _HASH_PATTERNS[algo].findall(text):
            hashes.setdefault(m.lower(), algo)
    hash_list = sorted(f"{algo}:{value}" for value, algo in hashes.items())

    ttps = sorted(set(_TTP_PATTERN.findall(text)))

    emails = sorted({m.group(0).lower() for m in _EMAIL_PATTERN.finditer(text)
                     if m.group(2).lower() in _TLDS})
    cves = sorted({m.group(0).upper() for m in _CVE_PATTERN.finditer(text)})
    wallets = sorted({w for pat in _WALLET_PATTERNS for w in pat.findall(text)})
    ip_ports = _extract_ip_ports(text, ips)

    return {"hashes": hash_list, "domains": domains, "ips": ips,
            "urls": urls, "emails": emails, "cves": cves, "wallets": wallets,
            "ip_ports": ip_ports,
            "ja4": [], "ja4s": [], "ja4h": [], "ja4l": [], "ja4x": [],
            "ja4t": [], "ja4ts": [], "ja4ssh": [], "jarm": [],
            "ttps": ttps}


def suggest_cluster_names(text: str, max_candidates: int = 5) -> list[str]:
    """Rank candidate threat-actor/malware names by mention frequency.
    Best-effort only — always let an explicit cluster_name from the
    caller/agent override this."""
    counts: Counter[str] = Counter()
    for pattern in _NAME_PATTERNS:
        for m in pattern.finditer(text):
            name = m.group(0).strip()
            name = re.sub(r"\s+", " ", name)
            counts[name] += 1
    ranked = [name for name, _ in counts.most_common(max_candidates)]
    return ranked
