---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	rank(rank)
	infra_change(infra_change)
	cert_tls(cert_tls)
	hosting(hosting)
	opendir(opendir)
	persist(persist)
	narrate(narrate)
	__end__([<p>__end__</p>]):::last
	__start__ --> rank;
	cert_tls --> persist;
	hosting --> persist;
	infra_change --> persist;
	opendir --> persist;
	persist --> narrate;
	rank --> cert_tls;
	rank --> hosting;
	rank --> infra_change;
	rank --> opendir;
	narrate --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
