---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	ingest_inbox(ingest_inbox)
	sweep(sweep)
	enrich_and_write(enrich_and_write)
	run_analytics(run_analytics)
	write_digest(write_digest)
	__end__([<p>__end__</p>]):::last
	__start__ --> ingest_inbox;
	enrich_and_write --> run_analytics;
	ingest_inbox -.-> sweep;
	run_analytics --> write_digest;
	sweep --> enrich_and_write;
	write_digest --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
